# Generated by Django 3.1.2 on 2021-01-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(blank=True, default=0)),
                ('diretor', models.CharField(default='', max_length=100)),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Ficção', 'Ficção')], default='Ação', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(auto_now=True)),
                ('fim', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.filme')),
            ],
        ),
    ]
